### PR TITLE
fix: swap to @jlab-contrib/msa

### LINKED ISSUE #258: [3.1.0rc2] `jupyterlab-fasta` fails to render: `t.on is not a function`
## Description

The `jupyterlab-fasta` extension does not work with `3.1.0rc2`

## Reproduce

Can be reproduced with this gist:

- https://gist.github.com/jtpio/844ab4e85ae84f230cbcb0e56a59c88e
- https://mybinder.org/v2/gist/jtpio/844ab4e85ae84f230cbcb0e56a59c88e/master?urlpath=/lab

image

## Expected behavior

The `jupyterlab-fasta` extensions should work out of the box with JupyterLab 3.1.

## Context

Originally reported by @bollwyvl in https://github.com/jupyterlite/jupyterlite/issues/284

- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox 89
- JupyterLab version: 3.1.0rc2

---- 
    
Originally opened as jupyterlab/jupyterlab#10675 by @jtpio, migration requested by @blink1073

### PR DESCRIPTION
**Pull request by zacharyrs**
Swap from the unmaintained [wilzbach/msa](https://github.com/wilzbach/msa) to a fork ([jupyterlab-contrib/msa](https://github.com/jupyterlab-contrib/msa)) with bugfixes.

This fixes issues with the MSA visualiser not displaying in new browsers.
running on my laptop

I've also reverted the `bio.io` dependency for `msa` to `v1.0.6` (https://github.com/jupyterlab-contrib/msa/commit/1d353efa5b59a94dc1edb14c97ecdfe9abfc99d8), which misses the latest `clustal` patches (https://github.com/wilzbach/bio.io/commit/233c569a000b4e481bc682dc1c5024aaa8f4c3b6).  
These were not included in the latest NPM build for `msa`, but might be worth later incorporating.
For this we'll need to fork `bio.io` too.

Hopefully everything is up to scratch!

Closes #258.

### CODE REVIEW

**Comment by zacharyrs** [comment]
Sorry I didn't open it in draft state!

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
@zacharyrs mind posting a quick screenshot in the top comment if you managed to get `jupyerlab-fasta` to run locally? (so it serves as reference, thanks!)

**Comment by zacharyrs** [comment]
Sure I'll do one tomorrow afternoon!

**Comment by zacharyrs** [comment]
@jtpio All done!

File: packages/fasta-extension/package.json [hunk 1]
```diff
@@ -55,7 +55,7 @@
     "@jupyterlab/rendermime-interfaces": "^3.0.5",
     "@lumino/messaging": "^1.4.3",
     "@lumino/widgets": "^1.16.1",
-    "msa": "^1.0.3"
+    "@jlab-contrib/msa": "^1.1.2"
```
Comment (jtpio) [inline packages/fasta-extension/package.json:58]: Looks like this new dependency should also have updated the top-level `yarn.lock` after running `jlpm` / `yarn` at the root of the repo?

Which means the following entry should normally be removed / updated?

https://github.com/jupyterlab/jupyter-renderers/blob/83e37757a4775054712bfe3da5d30cb9ef0fbef0/yarn.lock#L6100-L6123

Comment (zacharyrs) [reply packages/fasta-extension/package.json:58]: Should be all fixed - sorry it's been a while since I touched the JS ecosystem.

**Comment by jtpio** [comment]
Thanks!
